In [1]:
import numpy as np
array1 = np.array([1,2,3,4,5])
print(array1)

[1 2 3 4 5]


In [2]:
print(type(array1))

<class 'numpy.ndarray'>


## Slicing

In [3]:
array2 = np.array([12,45,32,56,67,8,99,98])

In [5]:
array2.dtype


dtype('int32')

In [6]:
arr = array2[4:6]
arr

array([67,  8])

In [7]:
arr[0] = 9

In [8]:
array2

array([12, 45, 32, 56,  9,  8, 99, 98])

In [9]:
arr = array2[4:6].copy()|

SyntaxError: invalid syntax (<ipython-input-9-6395504f8b74>, line 1)

In [10]:
arr

array([9, 8])

In [11]:
array2

array([12, 45, 32, 56,  9,  8, 99, 98])